'''
Print all subsequences of a string in Python
Given a string, we have to find out all subsequences of it.
A String is a subsequence of a given String, that is generated by 
deleting some character of a given string without changing its order.

Examples: 
1. abc -> a, b, c, ab, bc, ac, abc
2. aaa -> a, aa, aaa
'''

def getSubsequences(s):
    subsequences = []
    helper(s, 0, '')
    return subsequences


def dfs(s, i, subsequence, subsequences):
    if i == len(s):
        subsequences.append(subsequence)
    else:
        dfs(s, i+1, subsequence + s[i])
        dfs(s, i+1, subsequence)
